# -*- coding: utf-8 -*-
"""LOGISTIC REGRESSION model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xxQhRxle2Vo0ns4EFlLie8GnSashqjuo

# Import Libraries
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix, precision_recall_curve

emp=pd.read_csv("EmployeeData.csv")

emp = emp.rename(columns={'satisfaction_level': 'satisfaction', 
                        'last_evaluation': 'evaluation',
                        'number_project': 'projectCount',
                        'average_montly_hours': 'averageMonthlyHours',
                        'time_spend_company': 'yearsAtCompany',
                        'Work_accident': 'workAccident',
                        'promotion_last_5years': 'promotion',
                        'sales' : 'department',
                        'left' : 'turnover'
                        })

emp = emp[['turnover','satisfaction','evaluation','projectCount','averageMonthlyHours','yearsAtCompany','workAccident','promotion','department','salary'
         ]]

turnover_rate = emp.turnover.value_counts() / 14999
turnover_rate

salary = {'low':0, 'medium':1,'high':2}
emp['salary'] = emp['salary'].map(lambda x : salary[x])

emp_obj = pd.get_dummies(emp,\
        columns=['department'])
emp_obj

"""# TRAIN TEST SPLIT"""

from sklearn.preprocessing import MinMaxScaler
target_name = 'turnover'
X = emp_obj.drop('turnover', axis=1)
minmaxscaler = MinMaxScaler()
X=minmaxscaler.fit_transform(X)
y=emp_obj['turnover']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=30)

"""# LOGISTIC REGRESSION

Logistic regression is a supervised learning classification algorithm used to predict the probability of a target variable.

The nature of target or dependent variable is dichotomous, which means there would be only two possible classes
"""

from sklearn.linear_model import LogisticRegression
logit_model = LogisticRegression()
logit_model.fit(X_train, y_train)
y_pred=logit_model.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test, predict))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

